from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    ForeignKey,
    Index,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)
from sqlalchemy.dialects.mysql import LONGTEXT


metadata = MetaData()

writing_projects = Table(
    "writing_projects",
    metadata,
    Column("id", String(191), primary_key=True),
    Column("name", String(255), nullable=False),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Column("deleted_at", String(64), nullable=True),
    Index("idx_writing_projects_updated_at", "updated_at"),
    Index("idx_writing_projects_deleted_updated", "deleted_at", "updated_at"),
)

writing_materials = Table(
    "writing_materials",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), nullable=False),
    Column("filename", String(512), nullable=False),
    Column("stored_name", String(512), nullable=False),
    Column("content_type", String(120), nullable=True),
    Column("size", BigInteger, nullable=False, default=0),
    Column("sha256", String(128), nullable=True),
    Column("parsed_path", String(1024), nullable=True),
    Column("status", String(32), nullable=False),
    Column("error", Text, nullable=True),
    Column("parse_mode", String(32), nullable=True),
    Column("parser_version", String(64), nullable=True),
    Column("parse_source", String(32), nullable=True),
    Column("parsed_chars", Integer, nullable=False, default=0),
    Column("ocr_pages", Integer, nullable=False, default=0),
    Column("parsed_at", String(64), nullable=True),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Index("idx_writing_materials_project", "project_id"),
    Index("idx_writing_materials_project_created", "project_id", "created_at"),
    Index("idx_writing_materials_sha256", "sha256"),
)

writing_custom_sources = Table(
    "writing_custom_sources",
    metadata,
    Column("id", String(191), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), primary_key=True),
    Column("source_id", String(191), nullable=False),
    Column("intent_group_id", String(120), nullable=False, default=""),
    Column("intent_group", String(255), nullable=False, default=""),
    Column("keyword", String(255), nullable=False),
    Column("article_type", String(120), nullable=False),
    Column("title", String(512), nullable=False),
    Column("role", String(255), nullable=False),
    Column("brief_focus", Text, nullable=False),
    Column("channel", String(255), nullable=False),
    Column("channels_json", JSON, nullable=False),
    Column("status", String(32), nullable=False),
    Column("raw_json", JSON, nullable=False),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Index("uq_custom_project_source", "project_id", "source_id", unique=True),
    Index("idx_custom_project_created", "project_id", "created_at"),
    Index("idx_custom_project_keyword_type", "project_id", "keyword", "article_type"),
)

writing_intent_groups = Table(
    "writing_intent_groups",
    metadata,
    Column("id", String(120), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), primary_key=True),
    Column("name", String(255), nullable=False),
    Column("aliases_json", JSON, nullable=False),
    Column("keywords_json", JSON, nullable=False),
    Column("article_count", Integer, nullable=False, default=0),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Index("idx_intent_groups_project", "project_id"),
    Index("idx_intent_groups_project_name", "project_id", "name"),
)

writing_steps = Table(
    "writing_steps",
    metadata,
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), primary_key=True),
    Column("step", String(32), primary_key=True),
    Column("status", String(32), nullable=False),
    Column("input_json", JSON, nullable=False),
    Column("output_json", JSON, nullable=False),
    Column("error", Text, nullable=True),
    Column("confirmed_at", String(64), nullable=True),
    Column("updated_at", String(64), nullable=False),
    Index("idx_writing_steps_status", "step", "status"),
)

writing_jobs = Table(
    "writing_jobs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), nullable=False),
    Column("step", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("error", Text, nullable=True),
    Column("total_count", Integer, nullable=False, default=0),
    Column("completed_count", Integer, nullable=False, default=0),
    Column("failed_count", Integer, nullable=False, default=0),
    Column("skipped_count", Integer, nullable=False, default=0),
    Column("current_item", String(512), nullable=True),
    Column("message", Text, nullable=True),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Index("idx_writing_jobs_project", "project_id"),
    Index("idx_writing_jobs_project_created", "project_id", "created_at"),
    Index("idx_writing_jobs_status", "project_id", "status"),
    Index("idx_writing_jobs_step", "project_id", "step"),
)

writing_content_items = Table(
    "writing_content_items",
    metadata,
    Column("id", String(191), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), nullable=False),
    Column("step", String(32), nullable=False),
    Column("source_id", String(191), nullable=False),
    Column("source_step", String(32), nullable=False),
    Column("brief_id", String(191), nullable=False),
    Column("intent_group_id", String(120), nullable=False, default=""),
    Column("keyword", String(255), nullable=False),
    Column("article_type", String(120), nullable=False),
    Column("title", String(512), nullable=False),
    Column("status", String(32), nullable=False),
    Column("markdown", LONGTEXT().with_variant(Text, "sqlite"), nullable=True),
    Column("raw_json", JSON, nullable=False),
    Column("revision", Integer, nullable=False, default=1),
    Column("modified_at", String(64), nullable=True),
    Column("updated_at", String(64), nullable=False),
    Index("idx_content_project_step", "project_id", "step"),
    Index("idx_content_keyword_type", "project_id", "keyword", "article_type"),
    Index("idx_content_source", "project_id", "source_id"),
    Index("idx_content_brief", "project_id", "brief_id"),
)

writing_articles = Table(
    "writing_articles",
    metadata,
    Column("article_id", String(191), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), primary_key=True),
    Column("source_id", String(191), nullable=False),
    Column("source_step", String(32), nullable=False),
    Column("brief_id", String(191), nullable=False),
    Column("intent_group_id", String(120), nullable=False, default=""),
    Column("keyword", String(255), nullable=False),
    Column("article_type", String(120), nullable=False),
    Column("title", String(512), nullable=False),
    Column("markdown", LONGTEXT().with_variant(Text, "sqlite"), nullable=False),
    Column("status", String(32), nullable=False),
    Column("article_audit_status", String(32), nullable=False),
    Column("article_audited_at", String(64), nullable=True),
    Column("content_hash", String(128), nullable=False),
    Column("used", String(64), nullable=False),
    Column("review_notes", Text, nullable=True),
    Column("raw_json", JSON, nullable=False),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Index("idx_articles_project", "project_id"),
    Index("idx_articles_project_keyword_type", "project_id", "keyword", "article_type"),
    Index("idx_articles_audit", "project_id", "article_audit_status"),
    Index("idx_articles_source_step", "project_id", "source_step"),
    Index("idx_articles_content_hash", "content_hash"),
)

writing_matrix_import_drafts = Table(
    "writing_matrix_import_drafts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), nullable=False),
    Column("status", String(32), nullable=False),
    Column("filename", String(512), nullable=False),
    Column("stored_name", String(512), nullable=False),
    Column("content_type", String(120), nullable=True),
    Column("size", BigInteger, nullable=False, default=0),
    Column("source_path", String(1024), nullable=False),
    Column("job_id", String(64), nullable=True),
    Column("parsed_chars", Integer, nullable=False, default=0),
    Column("stats_json", JSON, nullable=False),
    Column("warnings_json", JSON, nullable=False),
    Column("output_json", JSON, nullable=False),
    Column("error", Text, nullable=True),
    Column("created_at", String(64), nullable=False),
    Column("updated_at", String(64), nullable=False),
    Column("applied_at", String(64), nullable=True),
    Index("idx_matrix_import_project", "project_id"),
    Index("idx_matrix_import_status", "project_id", "status"),
)

writing_logs = Table(
    "writing_logs",
    metadata,
    Column("id", BigInteger().with_variant(Integer, "sqlite"), primary_key=True, autoincrement=True),
    Column("project_id", String(191), ForeignKey("writing_projects.id", ondelete="CASCADE"), nullable=False),
    Column("message", Text, nullable=False),
    Column("created_at", String(64), nullable=False),
    Index("idx_writing_logs_project_time", "project_id", "created_at"),
)
